name: Swagger Api
title: "[Swagger]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: nombre
    attributes:
      label: Numéro pour le point du ticket 
      description: "Numéro du ticket"
      placeholder: "0,2,3"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Décrivez le problème rencontré" # Ajouté pour éviter que la description soit vide
    validations:
      required: true
  - type: dropdown
    id: type_code
    attributes:
      label: Front/Back
      description: "Choix à donner entre le back et le front"
      options:
        - Front
        - Back
    validations:
      required: true