name: Swagger Api
title: "[Swagger]: "
labels: []
body:
  - type: input
    id: titre
    attributes:
      label: Titre
      description: "Titre du ticket"
      placeholder: "Entrez le titre du ticket"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Décrivez le problème rencontré"
      placeholder: "Décrivez ici le problème..."
    validations:
      required: true
  - type: input
    id: nombre
    attributes:
      label: Nombre
      description: "Nombre que consomme le ticket"
      placeholder: "Entrez un nombre"
      render: number
    validations:
      required: true
  - type: dropdown
    id: type_code
    attributes:
      label: Front/Back
      description: "Choix à donner entre le back et le front"
      options:
        - Front
        - Back
    validations:
      required: true